# Generated by Django 2.2 on 2019-07-22 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'verbose_name': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Chaleco',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Chaleco',
                'verbose_name': 'Chaleco',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('total_horas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellido', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('celular', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)])),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(null=True, upload_to='uploads/foto_perfil/')),
                ('estado', models.BooleanField(default=True)),
                ('usuario_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=8)),
                ('satelites', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.Actividad')),
                ('registro_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.RegistroActividad')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroChaleco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('chaleco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.Chaleco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrackingApp.Usuario'),
        ),
    ]
